

#https://github.com/mariodosreis/tai


# This script calculates the **tRNA Adaptation Index (tAI)** for coding sequences (CDS) of a genome
# and generates associated plots. The process involves analyzing codon frequencies, codon usage, and
# tRNA gene counts. Below is a brief description of the main steps and how the script works.
#
# ------------------------------------------------------------------------------
#
# Prerequisites
#
# Before running the script, ensure that the following steps are completed:
#
# 1. **Generate Codon Frequency File:**
#    You need to use a Perl script (`codonM`) to generate codon frequencies from a CDS file. For example:
#    ```bash
#    perl codonM /path/to/your/cds/file.fna codon_frequencies_output
#    ```
#    - `codonM` generates a matrix of codon frequencies.
#    - The input file should be a genome's CDS sequences in FASTA format.
#    - The output file (`codon_frequencies_output`) is a table containing codon frequencies.
#
# 2. **Generate tRNA Gene Count File:**
#    You must first run **tRNAscan-SE** to extract the codon counts for tRNAs from your genome.
#    - The codons should be sorted in TCAG order.
#    - More information on this process can be found in the **gtAI** repository on GitHub.
#
# 3. **Prepare Codon Usage File:**
#    You should also generate a codon usage table using **CodonW** or **CodonZ** (for NC - Effective Number of Codons). Example:
#    ```bash
#    codonw /path/to/your/cds/file.fna codons_NC_output codons_NC_bulk -nomenu -nowarn -silent -enc -gc -gc3s -L_aa
#    ```
#    - The output of this step will be used to calculate NC (effective number of codons used in a sequence).
#
# ------------------------------------------------------------------------------
#
# Script Workflow
#
# 1. **Input Files:**
#    - `input1`: File containing tRNA gene counts (processed by Python script `count_genes_coding_tRNA.py`).
#    - `input2`: Codon frequencies file generated by `codonM` analysis.
#    - `input3`: Codon usage table file from **CodonZ** or **CodonW** analysis (with NC values).
#    - `output1`: File to store the calculated tAI for each protein.
#    - `output2`: File to store a summary of tAI and related metrics for the proteins.
#
# 2. **Processing the Data:**
#    - The script processes the input files to calculate the **relative adaptiveness values (RA)** for each tRNA
#      using the `get.ws()` function, excluding start and stop codons.
#    - The codon frequencies matrix is read, and **tAI** is calculated using the `get.tai()` function.
#    - The **NC (effective number of codons)** is calculated separately using CodonZ (or CodonW) results.
#
# 3. **Adding Length Bins:**
#    The script adds protein length bins (quantiles) based on the amino acid sequence length (L_aa), which are
#    then used for plotting and further analysis.
#
# 4. **Final Results:**
#    - The tAI values are combined with the NC and GC content in a data frame (`codons_NC_df`), and various
#      correlation analyses are performed, including:
#      - Pearson correlation between tAI and NC.
#      - Correlation between tAI, corrected NC, and GC content at the third codon position (GC3s).
#    - Two output files are generated:
#      - `output1`: A table containing tAI values and related information for each protein.
#      - `output2`: A summary file with the mean tAI, GC content, protein length, Pearson correlation,
#        and the intensity of translational selection (correlation between tAI, NC, and GC3).
#
# 5. **Charts (Optional):**
#    Several optional charts are available:
#    - **Histograms** of NC and tAI distributions.
#    - **Scatter plots** showing relationships between tAI, NC, and GC content.
#    - The script can also generate scatter plots with surrounding histograms (using the `ggMarginal` function if available).
#
#    Note: The plotting functionality requires the **ggplot2** and **viridis** libraries for generating color-coded charts.
#
# ------------------------------------------------------------------------------
#
# Usage
#
# To run the script, use the following command in your terminal:
# ```bash
# Rscript tAI.R <input1> <input2> <input3> <output1> <output2>
# ```
#    - `input1`: tRNA gene count file.
#    - `input2`: Codon frequencies file from the `codonM` analysis.
#    - `input3`: Codon usage table (NC values).
#    - `output1`: File for storing tAI results for each protein.
#    - `output2`: File for storing a summary of the analysis.
#
# Example
# ```bash
# Rscript tAI.R processed_tRNA_counts.txt codon_frequencies.txt codon_usage.txt tAI_results.txt summary_results.txt
# ```
#
# ------------------------------------------------------------------------------
#
# Notes
# - Make sure all input files are prepared according to the instructions provided in the **gtAI** repository.
# - The script assumes the input data is correctly formatted and prepared in advance.
# - The `ggplot2` package is used for generating plots, so ensure it's installed (`install.packages("ggplot2")`).
#
# ------------------------------------------------------------------------------
#
# This script is designed for use in genomic studies involving codon usage and tRNA adaptation, providing insight
# into translation efficiency and selection in various organisms.



require('tAI')
library(ggplot2)
# library(ggExtra) #used to create nice-looking scatter plot with joined two histograms paralleled to both axes
library(viridis)
# library(gridExtra)


args <- commandArgs(trailingOnly = TRUE)
input1 <- args[1] #processed tRNAscan-SE outbut by python script count_genes_coding_tRNA.py
input2 <- args[2] #output of codonM analysis.
input3 <- args[3] #output of codonZ/codonW analysis.
output1 <- args[4] #result. counted tAI and other information for each protein - dataframe
output2 <- args[5] #result. counted and summaried tAI and other information for each protein - dataframe

genes_coding_tRNA <- scan(input1) #file with counted genes coding tRNA #import file #64 len
codons_rav <- get.ws(tRNA = genes_coding_tRNA, sking = 0) #ignore START and STOP codons. Calculate relative adaptiveness values for each tRNA #sking = 0 for eukaryota. 


codons_frequencies <- matrix(scan(input2), ncol = 61, byrow = TRUE) #file from codonM analysis (by perl)
codons_frequencies <- codons_frequencies[,-33] #eliminates methionine
codons_tai <- get.tai(codons_frequencies, codons_rav) #calculating codon_tai for each sequence

print(input3)
codons_NC_df <- read.table(input3, header = TRUE, sep = "\t", na.strings = "*****", fill = FALSE, check.names = FALSE, stringsAsFactors = FALSE)  # Nie zamienia tekstów na faktory
# codons_NC_df <- read.table(input3, header = TRUE, na.strings = "*****", fill = TRUE, check.names = FALSE, sep = "\t", stringsAsFactors = FALSE)  # Nie zamienia tekstów na faktory
codons_NC_df[codons_NC_df == "*****"] <- NA
codons_NC_df <- codons_NC_df[, 1:5] #it removes last columns full of NA values idk what
codons_NC_df$title <- trimws(codons_NC_df$title)


codons_NC_df$L_aa <- as.numeric(codons_NC_df$L_aa)
unique(codons_NC_df$L_aa)
sum(is.na(codons_NC_df$L_aa))

sum(is.na(codons_NC_df$L_aa))

# Liczba wartości nie-NA
sum(!is.na(codons_NC_df$L_aa))

# Sprawdzamy, jakie są wartości w tej kolumnie
# table(codons_NC_df$L_aa)
# summary(codons_NC_df$L_aa)
# any(!is.na(codons_NC_df$L_aa))
# codons_NC_df$L_aa
codons_NC_df$L_aa[is.na(codons_NC_df$L_aa)] <- mean(codons_NC_df$L_aa, na.rm = TRUE)
# codons_NC_df$AA_len_bin <- cut(codons_NC_df$L_aa, breaks = quantile(codons_NC_df$L_aa, probs = c(0.00, 0.25, 0.75, 1.00), na.rm = TRUE), include.lowest = TRUE, labels = c("Q1", "Q2 + Q3", "Q4")) #adding labels with quantiles (second and third are joined) to aa length


breaks <- seq(min(codons_NC_df$L_aa, na.rm = TRUE),
              max(codons_NC_df$L_aa, na.rm = TRUE),
              length.out = 5)

# Przydzielanie kategorii
codons_NC_df$AA_len_bin <- cut(codons_NC_df$L_aa,
                                breaks = breaks,
                                include.lowest = TRUE,
                                labels = c("Q1", "Q2", "Q3", "Q4"))

codons_NC_df$tAI <- codons_tai #creates data frame with needed data to create plots

# Charts
# hist_nc <- ggplot(data = codons_NC_df, aes(x = Nc, fill = AA_len_bin))+
#     geom_histogram(binwidth = 1, color = 'black') +
#     scale_fill_viridis(discrete = TRUE, name = 'Protein Length Bin',
#                        labels = c('26 - 222.5 (Q1)', '225.5 - 524 (Q2 + Q3)', '524 - 3369 (Q4)'))+
#     labs(x = 'NC', y = 'Counts', title = "Distribution of Effective Number of Codons (NC) used in single sequence in Postia's CDS")+
#     theme_bw()+
#     theme(plot.title = element_text(size = 10, lineheight = 2), legend.position = 'top')
# # ggsave('charts/NC_hist_postia.png', plot = hist_nc, width = 8, height = 6, dpi = 300 )
# # hist_nc #okazalo sie ze robienie trzech wykresow i laczenie ich ze soba nie jest najlepszym pomyslem. Lepiej zrobic od razu gotowy wykres z dwoma dodatkowymi warstwami
# #scatter with two surrounding histograms paralelled to axes



# hist_tAI <- ggplot(data = codons_NC_df, aes(x = tAI, fill = AA_len_bin)) +
#     geom_histogram(binwidth = 0.01, color = 'black')+
#     scale_fill_viridis(discrete = TRUE, name = 'Protein Length Bin',
#                        labels = c('26 - 222.5 (Q1)', '225.5 - 524 (Q2 + Q3)', '524 - 3369 (Q4)'))+
#     labs(x = 'tAI', y = 'Counts', title = "Distribution of tRNA Adaptation Index (tAI) in Postia's CDS")+
#     theme_bw()+
#     theme(plot.title = element_text(size = 10, lineheight = 2), legend.position = 'top')

# # ggsave('charts/tAI_hist_postia.png', plot = hist_tAI, width = 8, height = 6, dpi = 300 )
# # hist_tAI


# GC_tAI_scatter <- ggplot(data = codons_NC_df, aes(x = GC, y = tAI, color = AA_len_bin))+
#     geom_point(size = 3, alpha = 0.6)+
#     geom_smooth(method = 'loess', se = FALSE, linewidth = 1)+
#     scale_colour_viridis(discrete = TRUE, name = 'Protein Length Bin',
#                        labels = c('26 - 222.5 (Q1)', '225.5 - 524 (Q2 + Q3)', '524 - 3369 (Q4)'))+
#     labs(x = 'GC percentage', y = 'tAI', title = "Distribution of tRNA Adaptation Index (tAI) and percantage of GC in Postia's CDS")+
#     theme_bw()+
#     theme(plot.title = element_text(size = 10, lineheight = 2), legend.position = 'top')
# # ggsave('charts/GC_tAI_hist_postia.png', plot = GC_tAI_scatter, width = 8, height = 6, dpi = 300 )
# # GC_tAI_scatter


# #scatter with two surrounding histograms paralelled to axes
# NC_tAI_scatter <- ggplot(codons_NC_df, aes(x = Nc, y = tAI, color = AA_len_bin))+
#     geom_point(size = 2, alpha = 0.6) +
#     # scale_color_manual(values = c("Q1" = '#ffa600', "Q2 + Q3" = '#bc5090', "Q4" = '#003f5c')) +
#     scale_color_viridis(discrete = TRUE, name = 'Protein Length Bin',
#                         labels = c('26 - 222.5 (Q1)', '225.5 - 524 (Q2 + Q3)', '524 - 3369 (Q4)'))+
#     labs(x = 'NC values', y = 'tAI values', title = "Distribution of tRNA Adaptation Index (tAI) and Effective Number of Codons (NC) in Postia's CDS")+
#     theme_bw()+
#     theme(plot.title = element_text(size = 10, lineheight = 2), legend.position = 'top')
# nc_tai_plot
# ggsave('charts/NC_tAI_scatter_postia.png', plot = NC_tAI_scatter, width = 8, height = 6, dpi = 300 )
# NC_tAI_scatter

#attention! ggMarginal from ggExtra is not available in server
# nc_tai_plot_with_ggMarginal <- ggMarginal(p = NC_tAI_scatter, type = 'histogram', colour = '#21918c', fill = '#21918c') #unfortunately, ggMarginal does not allow to modify histograms surrounding scatterplot in extent that able to change colours of bars depending of bins (quantiles)
# ggsave('charts/NC_tAI_scatter_postia_marginal.png', plot = nc_tai_plot_with_ggMarginal, width = 8, height = 6, dpi = 300 )


# empty_plot <- ggplot() #plot to place 'white/grey' space on right top corner  #unhash this fragment to make a plot using available packages.
# 
# grid.arrange(
#     hist_nc, empty_plot, NC_tAI_scatter, hist_tAI, 
#     ncol = 2, nrow = 2, 
#     widths = c(6, 2), heights = c(2, 6)
# )


#end plots


codons_pearson <- cor(codons_tai, codons_NC_df$Nc, use = "complete.obs") #p means pearson
cat('Correlation between tAI, ENC using Pearson equals: ', codons_pearson, '\n')


codons_s <- get.s(codons_tai, codons_NC_df$Nc, codons_NC_df$GC3s) #corelation between tAI, corrected Nc and GC3s (contents of GC pairs in 3rd place in codon). Its name is correlation S, because it reflects the intensity of translactional selection acting on our sample of genes
cat('Corelation between tAI, corrected Nc and GC3s (contents of GC pairs in 3rd place in codon). It reflects the intensity of translactional selection acting on our sample of genes and equeals:', codons_s, '\n')



all_proteins_summary_result <- data.frame(ID = input1, tAI_mean = mean(codons_NC_df$tAI, na.rm = TRUE), GC_mean = mean(codons_NC_df$GC, na.rm = TRUE), L_aa_mean = mean(codons_NC_df$L_aa, na.rm = TRUE), pearson = codons_pearson, correlation_tAI_NC_GC3 = codons_s)
all_proteins_summary_result <- na.omit(all_proteins_summary_result)

write.table(codons_NC_df, file = output1, append = FALSE, sep = '\t', row.names = FALSE, col.names = TRUE)
print(paste('Written file: ', output1))

write.table(all_proteins_summary_result, file = output2, append = FALSE, sep = '\t', row.names = FALSE, col.names = TRUE)
print(paste('Written file: ', output2))


# if (file.exists(output1)) {
#     print(paste('File', output1, 'already exists! Nothing happened'))
# } else {
#     write.table(codons_NC_df, file = output1, append = FALSE, sep = '\t', row.names = FALSE, col.names = TRUE)
# }


# if (file.exists(output2)) {
#     print(paste('File', output2, 'already exists! Nothing happened'))
# } else {
#     write.table(all_proteins_summary_result, file = output2, append = FALSE, sep = '\t', row.names = FALSE, col.names = TRUE)
# }
