
configfile: "config/config.yaml"

import pandas as pd
from glob import glob
from snakemake.utils import validate
from pathlib import Path

# fragment to use singularity/apptainer containers instead of conda
# import yaml

# with open("workflow/containers/containers.yaml") as f:
#     CONTAINERS = yaml.safe_load(f)


validate(config, "schemas/config.schema.yaml")


# ----------------------
# --- Path variables ---
# ----------------------
# Helper path variables for easier acces

DATA_CDS = config["paths"]["data_cds"]
DATA_GENOME = config["paths"]["data_genome"]
GCODES_TRNASCANSE = config['paths']['genetic_codes_trnascanse']
GCODES_TABLES = config['paths']['genetic_codes_tables'] # currently out of use

PER_GENOME = config['paths']['per_genome']
AGGREGATED = config['paths']['aggregated']
LOGS = config['paths']['logs']

DATA_MAINTABLE = config["paths"]["main_dataset"]
DATA_PLOTS = config["paths"]["plots"]
DATA_TABLES = config["paths"]["tables"]
REPORT_FILE = config["paths"]["reports"]



# ---------------------
# --- Samples table ---
# ---------------------
# Read samples from tsv
samples_df = pd.read_csv(config['paths']['samples'], sep = '\t')

# Validate samples tsv
validate(samples_df, "schemas/samples.schema.yaml")

samples_df = samples_df.set_index("sample")
samples_df = samples_df[samples_df['include']== True] # added additional column in samples.tsv to make excluding some samples much easier
SAMPLES = samples_df.index.tolist()


# -------------------------------
# ------- Helper functions ------
# -------------------------------
def resolve_single_file(pattern):
    matches = glob(pattern) # get list of path to proper file based on pattern

    if len(matches) == 0:
        raise FileNotFoundError(f"No file found for pattern: {pattern}")
    
    if len(matches)>1:
        raise ValueError(f'Multiple files found for pattern: {pattern}')
    
    return matches[0]


def get_genome(wildcards):
    pattern = samples_df.loc[wildcards.sample,'genome']
    return resolve_single_file(f"{DATA_GENOME}/{pattern}")
    

def get_cds(wildcards):
    pattern = samples_df.loc[wildcards.sample, 'cds']
    return resolve_single_file(f'{DATA_CDS}/{pattern}')

def get_genetic_code(wildcards):
    return int(samples_df.loc[wildcards.sample, "genetic_code"])

def get_trnascanse_code_arg(wildcards):
    ''' Function creates path to file with proper genetic code structure for tRNAscan-SE tool and returns argument.'''
    genetic_code = get_genetic_code(wildcards)

    if genetic_code == 1:
        return ""
    
    gcode_file = Path(GCODES_TRNASCANSE)/f'{genetic_code}.gcode'

    if not gcode_file.exists():
        raise FileNotFoundError(
            f'Not found tRNAscan-SE genetic code file in {GCODES_TRNASCANSE} location. Consider to change code or add your own file with proper structure:\n # The Alternative Yeast Nuclear Code (transl_table=12)\n# Format:  <Codon> <3-letter AA abreviation> <One letter AA abrev>\nCTG Ser S\n. ps. This file has to contain ONLY DNA, tRNA is forbidden '
        )
    
    return f"-g {gcode_file}"

def get_domain(wildcards):
    """Extract and normalize domain from samples.tsv."""
    domain = str(samples_df.loc[wildcards.sample, "domain"]).strip().lower()

    domain_map = {
        "eukarya": "Eukarya",
        "eukaryota": "Eukarya",
        "bacteria": "Bacteria",
        "archaea": "Archaea",
    }

    if domain not in domain_map:
        raise ValueError(
            f"Invalid domain for sample {wildcards.sample}: {domain}. "
            "Allowed values: Eukarya, Bacteria, Archaea."
        )

    return domain_map[domain]

# -----------------
# --- Main Rule ---
# -----------------

# DEPRECATED
# rule all:
#     input:
#         expand(
#             f'{PER_GENOME}/{{sample}}/codon_metrics/{{sample}}_summary.tsv',
#             sample = SAMPLES
#         )

rule all:
    input:
        # Per sample data
        expand(f'{PER_GENOME}/{{sample}}/codon_metrics/{{sample}}_summary.tsv', sample = SAMPLES),
        # Final reports
        f"{REPORT_FILE}/summary_report.html",
        f"{REPORT_FILE}/summary_report.md"


# ----------------------
# ---  Include rules ---
# ----------------------
include: "rules/trnascan_rule.smk"
include: "rules/clean_tRNAscanSE_output.smk"
include: "rules/prepare_trna_codon_counts_to_tai_rule.smk"
include: "rules/codon_usage_metrics_rule.smk"
# report rule 
include: "rules/aggregate_and_report.smk"




# ----------------------------------
# ---  Process data to count tAI ---
# ----------------------------------






# rule count_and_transform_trnas:
#     '''
#     Program reads table from tRNAscan-SE output and count previously complemented codons. Output is in format needed in gtAI (R).

#     !!!!!!!!!!! CHECK THIS INFORMATION BELOW!!!!!!!!!!!!!!!
#     Note: input Anti Codon is in DNA (as seq in input tRNAscan-SE)
#     '''
#     input:
#         # trnascanse ouptut
    
#     output:

#     shell:


