
configfile: "config/config.yaml"

import pandas as pd
from glob import glob
from snakemake.utils import validate
import yaml

with open("workflow/containers/containers.yaml") as f:
    CONTAINERS = yaml.safe_load(f)


validate(config, "workflow/schemas/config.schema.yaml")


# ----------------------
# --- Path variables ---
# ----------------------
# Helper path variables for easier acces

DATA_CDS = config["paths"]["data_cds"]
DATA_DOWN = config["paths"]["data_downsampled"]
DATA_GENOME = config["paths"]["data_genome"]

PER_GENOME = config['paths']['per_genome']
AGGREGATED = config['paths']['aggregated']
LOGS = config['paths']['logs']

DATA_MAINTABLE = config["paths"]["main_dataset"]
DATA_PLOTS = config["paths"]["plots"]
DATA_TABLES = config["paths"]["tables"]
REPORT_FILE = config["paths"]["reports"]


# ----------------------
# ---  Include rules ---
# ----------------------
include: "workflow/rules/trnascan_rule.smk"
include: "workflow/rules/clean_tRNAscanSE_output.smk"
include: "workflow/rules/prepare_trna_codon_counts_to_tai_rule.smk"
include: "workflow/rules/codon_usage_metrics_rule.smk"



# ---------------------
# --- Samples table ---
# ---------------------
# Read samples from tsv
samples_df = pd.read_csv(config['paths']['samples'], sep = '\t')

# Validate samples tsv
validate(samples_df, "workflow/schemas/config.schema.yaml")

samples_df = samples_df.set_index("sample")
samples_df = samples_df[samples_df['include']== True] # added additional column in samples.tsv to make excluding some samples much easier
SAMPLES = samples_df.index.tolist()


# -------------------------------
# ------- Helper functions ------
# -------------------------------
def resolve_single_file(pattern):
    matches = glob(pattern) # get list of path to proper file based on pattern

    if len(matches) == 0:
        raise FileNotFoundError(f"No file found for pattern: {pattern}")
    
    if len(matches)>1:
        raise ValueError(f'Multiple files found for pattern: {pattern}')
    
    return matches[0]


def get_genome(wildcards):
    pattern = samples_df.loc[wildcards.sample,'genome']
    return resolve_single_file(f"{DATA_GENOME}/{pattern}")
    

def get_cds(wildcards):
    pattern = samples_df.loc[wildcards.sample, 'cds']
    return resolve_single_file(f'{DATA_CDS}/{pattern}')


def get_downsampled_fasta(wildcards):
    pattern = samples_df.loc[wildcards.sample]['downsampled_fasta']    
    return resolve_single_file(f'{DATA_DOWN}/{pattern}')

def get_first_contig(wildcards):
    pattern = samples_df.loc[wildcards.sample]['first_contig']    
    return resolve_single_file(f'{DATA_DOWN}/{pattern}')


def get_bed(wildcards):
    pattern = samples_df.loc[wildcards.sample]['bed']
    return resolve_single_file(f'{DATA_DOWN}/{pattern}')

def get_genetic_code(wildcards):
    return int(samples_df.loc[wildcards.sample, "genetic_code"])


# -----------------
# --- Main Rule ---
# -----------------

rule all:
    input:
        expand(
            f'{PER_GENOME}/{{sample}}/counted_codons/{{sample}}_aaa_counts.tsv', sample=SAMPLES
)







# ----------------------------------
# ---  Process data to count tAI ---
# ----------------------------------






# rule count_and_transform_trnas:
#     '''
#     Program reads table from tRNAscan-SE output and count previously complemented codons. Output is in format needed in gtAI (R).

#     !!!!!!!!!!! CHECK THIS INFORMATION BELOW!!!!!!!!!!!!!!!
#     Note: input Anti Codon is in DNA (as seq in input tRNAscan-SE)
#     '''
#     input:
#         # trnascanse ouptut
    
#     output:

#     shell:


