# ---------------------
# --- Project Paths ---
# ---------------------

paths:
  data_cds: "data/CDS"
  data_downsampled: "data/downsampled"
  data_genome: "data/genome"
  data_main_table: "data/Main_Dataset.tsv"
  data_plots: "results/plots"
  data_tables: "results/tables"
  report_file: "results/report.md"

# ---------------------------
# --- Analysis Parameters ---
# ---------------------------

params:
  species:
    - "Zymoseptoria_tritici"
    - "Postia_placenta"
    - "Schizosaccharomyces_pombe"
    - "Aspergillus_nidulans_FGSC_A4"
    - "Malassezia_globosa_CBS_7966"
    - "Mucor_ambiguus"
    - "Neolecta_irregularis_DAH-3"
    - "Piromyces_finnis"
    - "Rhizoctonia_solani"
    - "Blumeria_graminis_f_sp_triticale"

  fungal_lifestyles:
    - "unspecified_saprotroph"
    - "nectar_tap_saprotroph"
    - "wood_saprotroph"
    - "animal_parasite"
    - "plant_pathogen"
    - "soil_saprotroph"
    - "ectomycorrhizal"
    - "mycoparasite"
    - "pollen_saprotroph"
    - "arbuscular_mycorrhizal"
    - "litter_saprotroph"
    - "dung_saprotroph"
    - "protistan_parasite"
    - "animal_endosymbiont"
    - "algal_parasite"
    - "lichenized"

  kingdoms:
    - "Fungi"

  fungal_phyla:
    - "Ascomycota"
    - "Basidiobolomycota"
    - "Basidiomycota"
    - "Blastocladiomycota"
    - "Chytridiomycota"
    - "Entomophthoromycota"
    - "Glomeromycota"
    - "Kickxellomycota"
    - "Microsporidia"
    - "Monoblepharomycota"
    - "Mortierellomycota"
    - "Mucoromycota"
    - "Neocallimastigomycota"
    - "Olpidiomycota"
    - "Rozellomycota"
    - "Zoopagomycota"

  name_mapping:
    Ztritici: "Zymoseptoria_tritici"
    Pplacenta: "Postia_placenta"
    Spombe: "Schizosaccharomyces_pombe"
    Anidulans: "Aspergillus_nidulans_FGSC_A4"
    Mglobosa: "Malassezia_globosa_CBS_7966"
    Mambiguus: "Mucor_ambiguus"
    Nirregularis: "Neolecta_irregularis_DAH-3"
    Pfinnis: "Piromyces_finnis"
    Rsolani: "Rhizoctonia_solani"
    Bgraminis: "Blumeria_graminis_f_sp_triticale"

  phylum_mapping:
    Ztritici: "Ascomycota"
    Pplacenta: "Basidiomycota"
    Spombe: "Ascomycota"
    Anidulans: "Ascomycota"
    Mglobosa: "Basidiomycota"
    Mambiguus: "Mucoromycota"
    Nirregularis: "Ascomycota"
    Pfinnis: "Neocallimastigomycota"
    Rsolani: "Basidiomycota"
    Bgraminis: "Ascomycota"

  lifestyle_mapping:
    Ztritici: "plant_pathogen"
    Pplacenta: "wood_saprotroph"
    Spombe: "nectar_tap_saprotroph"
    Anidulans: "unspecified_saprotroph"
    Mglobosa: "soil_saprotroph"
    Mambiguus: "soil_saprotroph"
    Nirregularis: "unspecified_saprotroph"
    Pfinnis: "animal_endosymbiont"
    Rsolani: "plant_pathogen"
    Bgraminis: "plant_pathogen"

  kingdom_mapping:
    Ztritici: "Fungi"
    Pplacenta: "Fungi"
    Spombe: "Fungi"



samples:
  Ztritici:
    species: "Zymoseptoria_tritici"
    accession: "GCA_000219625.1"
    kingdom: "Fungi"
    phylum: "Ascomycota"
    lifestyle: "plant_pathogen"

  Pplacenta:
    species: "Postia_placenta"
    accession: "GCA_000006255.1"
    kingdom: "Fungi"
    phylum: "Basidiomycota"
    lifestyle: "wood_saprotroph"

  Spombe:
    species: "Schizosaccharomyces_pombe"
    accession: "GCA_000002945.2"
    kingdom: "Fungi"
    phylum: "Ascomycota"
    lifestyle: "nectar_tap_saprotroph"

  Anidulans:
    species: "Aspergillus_nidulans_FGSC_A4"
    accession: "GCA_000149205.2"
    kingdom: "Fungi"
    phylum: "Ascomycota"
    lifestyle: "unspecified_saprotroph"

  Mglobosa:
    species: "Malassezia_globosa_CBS_7966"
    accession: "GCA_000181695.1"
    kingdom: "Fungi"
    phylum: "Basidiomycota"
    lifestyle: "soil_saprotroph"

  Pfinnis:
    species: "Piromyces_finnis"
    accession: "GCA_002104945.1"
    kingdom: "Fungi"
    phylum: "Neocallimastigomycota"
    lifestyle: "animal_endosymbiont"

  Rsolani:
    species: "Rhizoctonia_solani"
    accession: "GCA_016906535.1"
    kingdom: "Fungi"
    phylum: "Basidiomycota"
    lifestyle: "plant_pathogen"

  Bgraminis:
    species: "Blumeria_graminis_f_sp_triticale"
    accession: "GCA_905067625.1"
    kingdom: "Fungi"
    phylum: "Ascomycota"
    lifestyle: "plant_pathogen"