# workflow/profiles/default/config.yaml

snakefile: workflow/Snakefile
configfile: config/config.yaml

cores: 32
printshellcmds: true
show-failed-logs: true
use-conda: true
conda-frontend: mamba
use-apptainer: false
rerun-incomplete: true
keep-going: true
latency-wait: 120