# ---------------------
# --- Project Paths ---
# ---------------------


paths:
  # input file 
  data_cds: "data/norbert_data/input/CDS"
  data_genome: "data/norbert_data/input/genome"
  genetic_codes_trnascanse: "data/norbert_data/input/genetic_codes/trnascanse"
  genetic_codes_tables: "data/norbert_data/input/tables"

  # samples metadata and datasets
  # samples -> datatset, main_dataset->samples
  metadata_dataset: "data/norbert_data/input/metadata/dataset.tsv"
  metadata_samples: "data/norbert_data/input/metadata/samples_test.tsv"

  # tmp script files 
  results: "data/norbert_data/output/"
  logs: "data/norbert_data/output/logs"
  benchmarks: "data/norbert_data/output/benchmarks"

  # output folders 
  per_genome: "data/norbert_data/output/per_genome"
  aggregated: "data/norbert_data/output/aggregated"

  # report results. 
  plots: "data/norbert_data/output/aggregated/plots"
  tables: "data/norbert_data/output/aggregated/tables"
  reports: "data/norbert_data/output/aggregated/reports"




# ---------------------------
# --- Analysis Parameters ---
# ---------------------------

# --- Report configuration ---
report_config:
  # path for report template 
  template_path: workflow/scripts/report_template.Rmd


# --- Tools parameters ---
trnascanse:
  threads: 8
  max_sensitivity: True # set it later into true
  domain: "-E" # allowed: E- eukaryotic, A-Archaea, B-Bacteria

trnascanse_clean:
  keep_pseudo: false #remove trnas recognized as pseudogenes
  remove_nnn: true #remove undetermined tRNAs from output


# --- Other parameters ---
params:

  # --- Taxonomic parameters ---
  kingdom_filter: "Fungi"

  allowed_phyla:
    - "Ascomycota"
    - "Basidiobolomycota"
    - "Basidiomycota"
    - "Blastocladiomycota"
    - "Chytridiomycota"
    - "Entomophthoromycota"
    - "Glomeromycota"
    - "Kickxellomycota"
    - "Microsporidia"
    - "Monoblepharomycota"
    - "Mortierellomycota"
    - "Mucoromycota"
    - "Neocallimastigomycota"
    - "Olpidiomycota"
    - "Rozellomycota"
    - "Zoopagomycota"

  allowed_lifestyles:
    - "unspecified_saprotroph"
    - "nectar_tap_saprotroph"
    - "wood_saprotroph"
    - "animal_parasite"
    - "plant_pathogen"
    - "soil_saprotroph"
    - "ectomycorrhizal"
    - "mycoparasite"
    - "pollen_saprotroph"
    - "arbuscular_mycorrhizal"
    - "litter_saprotroph"
    - "dung_saprotroph"
    - "protistan_parasite"
    - "animal_endosymbiont"
    - "algal_parasite"
    - "lichenized"

