#!/usr/bin/env python3

"""
Extract nucleotide CDS records selected as ribosomal reference sequences.

The script reads a CDS FASTA file and a plain-text list of exact CDS record
identifiers generated by the KofamScan parsing step. Only records whose
``SeqRecord.id`` occurs in the identifier list are written to the output
FASTA.

The identifier list must contain CDS FASTA record IDs, not gene identifiers
or protein identifiers. For NCBI CDS FASTA files, an expected identifier may
look like::

    lcl|EQ966233.1_cds_EED85936.1_1

The script validates that:

1. the requested CDS identifier list is not empty;
2. every requested identifier occurs in the input CDS FASTA;
3. CDS identifiers in the input FASTA are unique;
4. at least one CDS record is selected;
5. the number of written records equals the number of requested identifiers.

Snakemake inputs
----------------
cds
    Input nucleotide CDS FASTA file.
cds_ids
    Text file containing one exact CDS FASTA record identifier per line.

Snakemake output
----------------
cds
    FASTA file containing coding sequences selected as the cytosolic
    ribosomal reference set.

Why this script is required
---------------------------
KofamScan identifies functions using protein sequences, but CAI and other
codon-usage calculations require nucleotide coding sequences. The preceding
mapping and parsing stages convert significant protein annotations to exact
CDS record identifiers. This script performs the final extraction from the
original CDS FASTA.
"""

import gzip
from pathlib import Path

from Bio import SeqIO


def open_fasta(path: Path):
    """Open an uncompressed or gzip-compressed FASTA file in text mode."""
    if path.suffix == ".gz":
        return gzip.open(path, "rt", encoding="utf-8")

    return path.open("r", encoding="utf-8")


def main() -> None:
    cds_path = Path(snakemake.input.cds)
    cds_ids_path = Path(snakemake.input.cds_ids)
    output_path = Path(snakemake.output.cds)

    wanted = {
        line.strip()
        for line in cds_ids_path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    }

    if not wanted:
        raise RuntimeError(f"No CDS identifiers found in {cds_ids_path}")

    selected = []
    observed_requested: set[str] = set()
    observed_all: set[str] = set()
    duplicate_ids: set[str] = set()

    with open_fasta(cds_path) as handle:
        for record in SeqIO.parse(handle, "fasta"):
            if record.id in observed_all:
                duplicate_ids.add(record.id)

            observed_all.add(record.id)

            if record.id in wanted:
                selected.append(record)
                observed_requested.add(record.id)

    if duplicate_ids:
        examples = ", ".join(sorted(duplicate_ids)[:20])

        raise RuntimeError(
            f"{len(duplicate_ids)} duplicate CDS identifiers "
            f"were found in {cds_path}. Examples: {examples}"
        )

    missing = wanted - observed_requested

    if missing:
        examples = ", ".join(sorted(missing)[:20])

        raise RuntimeError(
            f"{len(missing)} requested ribosomal CDS identifiers "
            f"were not found in {cds_path}. Examples: {examples}"
        )

    if not selected:
        raise RuntimeError("No ribosomal reference CDS records were selected")

    if len(selected) != len(wanted):
        raise RuntimeError(
            "Selected CDS count does not match the requested identifier "
            f"count: selected={len(selected)}, requested={len(wanted)}"
        )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    temporary_output = output_path.with_suffix(output_path.suffix + ".tmp")

    written = SeqIO.write(
        selected,
        temporary_output,
        "fasta",
    )

    if written != len(wanted):
        temporary_output.unlink(missing_ok=True)

        raise RuntimeError(
            f"Biopython wrote {written} CDS records, "
            f"but {len(wanted)} were expected"
        )

    temporary_output.replace(output_path)

    print(f"input_cds: {cds_path}")
    print(f"requested_cds_ids: {len(wanted)}")
    print(f"selected_cds_records: {len(selected)}")
    print(f"output_cds: {output_path}")


if __name__ == "__main__":
    main()
