# workflow/profiles/apptainer/config.yaml

snakefile: workflow/Snakefile
configfile: config/config.yaml

cores: 8
printshellcmds: true
show-failed-logs: true
use-conda: false
use-apptainer: true
apptainer-prefix: "resources/containers"
apptainer-args: "--cleanenv"
rerun-incomplete: true
keep-going: false
latency-wait: 60